#!/usr/bin/env bash
# =====================================================
# FILE: openhands/scripts/open_final_pr.sh
# PURPOSE:
#   Open exactly ONE final PR after all gates pass.
# =====================================================

set -e

REPO_ROOT="${REPO_ROOT:-/workspace}"
BRANCH_NAME="${BRANCH_NAME:-lovable-autonomous-upgrade}"
BASE_BRANCH="${BASE_BRANCH:-main}"

cd "$REPO_ROOT"

echo "📤 Opening Final PR"
echo "   Branch: $BRANCH_NAME"
echo "   Base: $BASE_BRANCH"
echo ""

# Ensure we're in a git repo
if [ ! -d .git ]; then
  echo "❌ Error: Not a git repository"
  exit 1
fi

# Get current branch
current_branch=$(git branch --show-current)

echo "Current branch: $current_branch"

# If not on the upgrade branch, create and switch to it
if [ "$current_branch" != "$BRANCH_NAME" ]; then
  echo "Creating branch: $BRANCH_NAME"
  git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
fi

# Stage all changes
echo "Staging changes..."
git add .

# Check if there are changes to commit
if git diff --staged --quiet; then
  echo "ℹ️  No changes to commit"
else
  # Commit changes
  echo "Committing changes..."
  git commit -m "feat: autonomous Lovable upgrade to TanStack architecture

This PR contains the full autonomous upgrade performed by Agent Zero:
- Migrated to TanStack Router for type-safe routing
- Migrated to TanStack Query for data fetching
- Upgraded backend architecture to be authoritative
- All gates passed: install, lint, typecheck, test, build, e2e, visual

Generated by: lovable_autonomous_upgrade_v1
Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
"
fi

# Push branch
echo "Pushing branch to origin..."
git push -u origin "$BRANCH_NAME" --force-with-lease

# Create PR using GitHub CLI if available
if command -v gh &> /dev/null; then
  echo "Creating PR with GitHub CLI..."

  pr_body="## 🤖 Autonomous Lovable Upgrade

This PR was generated by the \`lovable_autonomous_upgrade_v1\` skill running in Agent Zero.

### Changes
- ✅ Migrated to **TanStack Router** for type-safe, file-based routing
- ✅ Migrated to **TanStack Query** for intelligent data fetching and caching
- ✅ Upgraded backend architecture (backend-authoritative pattern)
- ✅ All acceptance gates passed

### Gates Passed
- [x] install (pnpm i --frozen-lockfile)
- [x] lint (pnpm lint)
- [x] typecheck (pnpm typecheck)
- [x] test (pnpm test)
- [x] build (pnpm build)
- [x] e2e (pnpm e2e)
- [x] visual (pnpm visual)

### Architecture
- **Frontend**: React + Vite + TypeScript + TanStack
- **Backend**: Node.js + Hono (authoritative)
- **Database**: PostgreSQL + Redis

### Review Checklist
- [ ] Review TanStack Router migration
- [ ] Review TanStack Query integration
- [ ] Verify authentication flows
- [ ] Test all critical user paths
- [ ] Review backend API changes

Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
"

  if gh pr create --title "feat: Autonomous Lovable Upgrade to TanStack Architecture" \
                  --body "$pr_body" \
                  --base "$BASE_BRANCH" \
                  --head "$BRANCH_NAME"; then
    echo "✅ PR created successfully!"
  else
    echo "⚠️  Failed to create PR with gh CLI, but branch pushed successfully"
    echo "   Please create the PR manually at:"
    echo "   $(git remote get-url origin | sed 's/\.git$//')/compare/$BASE_BRANCH...$BRANCH_NAME"
  fi
else
  echo "⚠️  GitHub CLI (gh) not found"
  echo "   Branch pushed successfully. Create PR manually at:"
  echo "   $(git remote get-url origin | sed 's/\.git$//')/compare/$BASE_BRANCH...$BRANCH_NAME"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ FINAL PR READY FOR REVIEW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
